export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const FETCH_EVENTS = 'FETCH_EVENTS';

export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const ASYNC_ACTION_START = 'ASYNC_ACTION_START';
export const ASYNC_ACTION_FINISH = 'ASYNC_ACTION_FINISH';
export const ASYNC_ACTION_ERROR = 'ASYNC_ACTION_ERROR';
export const ASYNC_APP_LOADED = 'ASYNC_APP_LOADED';

export const CURRENT_USER_PROFILE = 'CURRENT_USER_PROFILE';
export const SELECTED_USER_PROFILE = 'SELECTED_USER_PROFILE';
export const CURRENT_USER_PHOTOS = 'CURRENT_USER_PHOTOS';